import { ReactQueryClientProvider } from "@/lib/react-query";
import { ToastProvider } from "@/providers/toast-provider";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import MaxWidth from "@/components/layout/max-width";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <link
          href="https://fonts.googleapis.com/css2?family=Abril+Fatface&display=swap"
          rel="stylesheet"
        ></link>
      </head>
      <body className={inter.className}>
        <ReactQueryClientProvider>
          <ToastProvider />
          <MaxWidth>{children}</MaxWidth>
        </ReactQueryClientProvider>
      </body>
    </html>
  );
}
